version: "3.9"

services:
  devopsdb:
    image: sireesha010491/vprofile-db:latest
    container_name: vprofile-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devopspassword
      MYSQL_DATABASE: accounts
    networks:
      - mynetwork

  application:
    image: sireesha010491/vprofile-app:latest
    container_name: vprofile-app
    restart: unless-stopped
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
